copy "..\..\nel\lib\nel_drv_direct3d_win_d.dll" "..\client\nel_drv_direct3d_win_d.dll"
copy "..\..\nel\lib\nel_drv_dsound_win_d.dll" "..\client\nel_drv_dsound_win_d.dll"
copy "..\..\nel\lib\nel_drv_opengl_win_d.dll" "..\client\nel_drv_opengl_win_d.dll"
copy "..\..\nel\lib\nel_drv_fmod_win_d.dll" "..\client\nel_drv_fmod_win_d.dll"
copy "..\..\nel\lib\nel_drv_openal_win_d.dll" "..\client\nel_drv_openal_win_d.dll"
