/////////////////////////////////////////////////////////////////////////////
// Name:        frmobjectviewer.h
// Purpose:     
// Author:      Matt Raykowski
// Modified by: 
// Created:     Wed 14 Nov 2007 12:10:45 CST
// RCS-ID:      
// Copyright:   Copyright, 2007 Matt Raykowski
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 14 Nov 2007 12:10:45 CST

#ifndef _FRMOBJECTVIEWER_H_
#define _FRMOBJECTVIEWER_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/toolbar.h"
#include "wx/splitter.h"
#include "wx/glcanvas.h"
#include "wx/statusbr.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRMOBJECTVIEWER 10000
#define ID_MENUITEM 10004
#define ID_TOOLBAR1 10002
#define ID_CHOICE1 10005
#define ID_SPLITTERWINDOW -1
#define ID_PANEL1 10006
#define ID_PANEL2 10007
#define ID_GLCANVAS1 10008
#define ID_STATUSBAR1 10003
#define SYMBOL_FRMOBJECTVIEWER_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMAXIMIZE|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxCLOSE_BOX
#define SYMBOL_FRMOBJECTVIEWER_TITLE _("OpenNeL Object Viewer")
#define SYMBOL_FRMOBJECTVIEWER_IDNAME ID_FRMOBJECTVIEWER
#define SYMBOL_FRMOBJECTVIEWER_SIZE wxSize(800, 600)
#define SYMBOL_FRMOBJECTVIEWER_POSITION wxPoint(1, 1)
////@end control identifiers


/*!
 * frmObjectViewer class declaration
 */

class frmObjectViewer: public wxFrame
{    
    DECLARE_CLASS( frmObjectViewer )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    frmObjectViewer();
    frmObjectViewer( wxWindow* parent, wxWindowID id = SYMBOL_FRMOBJECTVIEWER_IDNAME, const wxString& caption = SYMBOL_FRMOBJECTVIEWER_TITLE, const wxPoint& pos = SYMBOL_FRMOBJECTVIEWER_POSITION, const wxSize& size = SYMBOL_FRMOBJECTVIEWER_SIZE, long style = SYMBOL_FRMOBJECTVIEWER_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FRMOBJECTVIEWER_IDNAME, const wxString& caption = SYMBOL_FRMOBJECTVIEWER_TITLE, const wxPoint& pos = SYMBOL_FRMOBJECTVIEWER_POSITION, const wxSize& size = SYMBOL_FRMOBJECTVIEWER_SIZE, long style = SYMBOL_FRMOBJECTVIEWER_STYLE );

    /// Destructor
    ~frmObjectViewer();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin frmObjectViewer event handler declarations

////@end frmObjectViewer event handler declarations

////@begin frmObjectViewer member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end frmObjectViewer member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin frmObjectViewer member variables
////@end frmObjectViewer member variables
};

#endif
    // _FRMOBJECTVIEWER_H_
