/////////////////////////////////////////////////////////////////////////////
// Name:        frmobjectviewer.cpp
// Purpose:     
// Author:      Matt Raykowski
// Modified by: 
// Created:     Wed 14 Nov 2007 12:10:45 CST
// RCS-ID:      
// Copyright:   Copyright, 2007 Matt Raykowski
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 14 Nov 2007 12:10:45 CST

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "frmobjectviewer.h"

////@begin XPM images
////@end XPM images


/*!
 * frmObjectViewer type definition
 */

IMPLEMENT_CLASS( frmObjectViewer, wxFrame )


/*!
 * frmObjectViewer event table definition
 */

BEGIN_EVENT_TABLE( frmObjectViewer, wxFrame )

////@begin frmObjectViewer event table entries
////@end frmObjectViewer event table entries

END_EVENT_TABLE()


/*!
 * frmObjectViewer constructors
 */

frmObjectViewer::frmObjectViewer()
{
    Init();
}

frmObjectViewer::frmObjectViewer( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create( parent, id, caption, pos, size, style );
}


/*!
 * frmObjectViewer creator
 */

bool frmObjectViewer::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin frmObjectViewer creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end frmObjectViewer creation
    return true;
}


/*!
 * frmObjectViewer destructor
 */

frmObjectViewer::~frmObjectViewer()
{
////@begin frmObjectViewer destruction
////@end frmObjectViewer destruction
}


/*!
 * Member initialisation
 */

void frmObjectViewer::Init()
{
////@begin frmObjectViewer member initialisation
////@end frmObjectViewer member initialisation
}


/*!
 * Control creation for frmObjectViewer
 */

void frmObjectViewer::CreateControls()
{    
////@begin frmObjectViewer content construction
    // Generated by DialogBlocks, Wed 14 Nov 2007 13:33:34 CST (unregistered)

    frmObjectViewer* itemFrame1 = this;

    wxMenuBar* menuBar = new wxMenuBar;
    wxMenu* itemMenu3 = new wxMenu;
    itemMenu3->Append(ID_MENUITEM, _("Open"), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu3, _("File"));
    itemFrame1->SetMenuBar(menuBar);

    wxToolBar* itemToolBar5 = CreateToolBar( wxTB_FLAT|wxTB_HORIZONTAL, ID_TOOLBAR1 );
    wxBitmap itemtool6Bitmap(wxNullBitmap);
    wxBitmap itemtool6BitmapDisabled;
    itemToolBar5->AddTool(ID_CHOICE1, _T(""), itemtool6Bitmap, itemtool6BitmapDisabled, wxITEM_NORMAL, _T(""), wxEmptyString);
    itemToolBar5->Realize();
    itemFrame1->SetToolBar(itemToolBar5);

    wxSplitterWindow* itemSplitterWindow7 = new wxSplitterWindow( itemFrame1, ID_SPLITTERWINDOW, wxDefaultPosition, wxSize(100, 100), wxSP_3DBORDER|wxSP_3DSASH|wxNO_BORDER );
    itemSplitterWindow7->SetMinimumPaneSize(0);

    wxPanel* itemPanel8 = new wxPanel( itemSplitterWindow7, ID_PANEL1, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );

    wxPanel* itemPanel9 = new wxPanel( itemSplitterWindow7, ID_PANEL2, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    wxGLCanvas* itemGLCanvas10 = new wxGLCanvas( itemPanel9, ID_GLCANVAS1, wxDefaultPosition, wxDefaultSize, wxNO_BORDER );

    itemSplitterWindow7->SplitHorizontally(itemPanel8, itemPanel9, 50);

    wxStatusBar* itemStatusBar11 = new wxStatusBar( itemFrame1, ID_STATUSBAR1, wxST_SIZEGRIP|wxNO_BORDER );
    itemStatusBar11->SetFieldsCount(2);
    itemFrame1->SetStatusBar(itemStatusBar11);

////@end frmObjectViewer content construction

    itemSplitterWindow7->SetSplitMode(wxSPLIT_VERTICAL);
}


/*!
 * Should we show tooltips?
 */

bool frmObjectViewer::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap frmObjectViewer::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin frmObjectViewer bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end frmObjectViewer bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon frmObjectViewer::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin frmObjectViewer icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end frmObjectViewer icon retrieval
}
